### ISSUE TITLE
请问怎么升级到python3.0?

### ISSUE THREAD

**Issue by jaydenjd** [c782464295/ksdanmu#10]
我试过将您2.0的代码的语法升级到3.0，但是似乎这样有问题？

**Comment by codeman1989** [comment]
没试过，不知道。

**Comment by jaydenjd** [comment]
好的。谢谢啦。如果有这方便相关的资料，麻烦告知下。非常感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sw-eety"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 中午11:19
收件人:&nbsp;"c782464295/ksdanmu"<ksdanmu@noreply.github.com&gt;;
抄送:&nbsp;"゛平清淡淡"<282669595@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [c782464295/ksdanmu] 请问怎么升级到python3.0? (#10)




没试过，不知道。
