### ISSUE TITLE
现在不能用了，连接上并没有返回信息。

### ISSUE THREAD

**Issue by tcc0lin** [c782464295/ksdanmu#11]

**Comment by codeman1989** [comment]
2020.4.27日html版测试可以，在控制台中可以看到返回，streamid需要获取。提示断开是因为steamid无效或直播已经关闭。

**Comment by tcc0lin** [comment]
> 2020.4.27日html版测试可以，在控制台中可以看到返回，streamid需要获取。提示断开是因为steamid无效或直播已经关闭。

好的，没有试html版本，python版本已经失效，websocket地址以及header都改变了，而且不知道是websocket库变了还是其他的，传的参数都有问题，直接报错

**Comment by codeman1989** [comment]
websocket地址没变，pip install websocket-client。
