### ISSUE TITLE
python版本现在不能用了吗？

### ISSUE THREAD

**Issue by eleeeeeee** [c782464295/ksdanmu#3]

**Comment by eleeeeeee** [comment]
error from callback <function on_open at 0x0BB2C1E0>: 'list' object has no attribute '__buffer__'

**Comment by codeman1989** [comment]
8.13可用 python27

**Comment by codeman1989** [comment]
8.18 18点测试可用

**Comment by eleeeeeee** [comment]
我把thread改成_thread  用python3.6跑
error from callback <function on_open at 0x0BD1E1E0>: 'list' object has no attribute '__buffer__' 
Connection is already closed.
### closed ###
然后就error了

**Comment by willshion** [comment]
python 3.5 thread改成 threading
