### ISSUE TITLE
现在直接拉下你的代码跑好像没结果出来，还有part1、part3指的是什么呢？

### ISSUE THREAD

**Issue by jaydenjd** [c782464295/ksdanmu#6]
现在直接拉下你的代码跑好像没结果出来，还有part1、part3指的是什么呢？

**Comment by codeman1989** [comment]
part1 3 固定

**Comment by jaydenjd** [comment]
> part1 3 固定

你那边跑起来可以出现弹幕吗？我这边跑了没反应？还有请问下你是用什么抓包的，我自己尝试了很多办法，都没办法抓到websockt的包

**Comment by codeman1989** [comment]
可以，需要更换part2为开播的streamID。wss抓包的工具和方法可以自行百度

**Comment by jaydenjd** [comment]
> 可以，需要更换part2为开播的streamID。wss抓包的工具和方法可以自行百度

我将正在开播liveStreamID 用ord转成ACSII码，换上你的那个test.py的part2，其他没改，但是还是没用。
可以加下你qq吗？或者你加我的可以吗？282669595，万分感谢，我已经搞了好多天这个了

**Comment by jaydenjd** [comment]
你好，我用网页打开直播，用fiddler来抓包，抓到了websoct的包，但是我发现，那一段一开始发送的16进制，应该就是对应你的Part1，part2，part3，其中part1是固定的，part2是liveStreamId，part3是一段可变的（是随机的吗？没发现规律）加请求的时间戳。然后请求时需要有一个心跳包，#             就是你的这个ws.send([8, 1, 26, 7, 8, 184, 232, 190, 199, 220, 44], 0x2)。
以上分析对吗？
